version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kronos-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models
    environment:
      - API_PORT=8000
      - CORS_ORIGINS=http://localhost,http://localhost:3000
      - DEFAULT_DEVICE=cpu
    networks:
      - kronos-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kronos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - kronos-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: kronos-redis
    ports:
      - "6379:6379"
    networks:
      - kronos-network
    restart: unless-stopped

networks:
  kronos-network:
    driver: bridge
